import { useState } from "react";
import { ArrowRight, BadgeCheck, Check, ClipboardCheck, ShieldAlert, Users } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { naira } from "@/lib/priceData";
import { PageIntro, type ShellUser } from "@/components/PriceNaijaShell";

export default function AdminPage({ user, section = "overview" }: { user: ShellUser; section?: string }) {
  const admin = user?.accountRole === "admin";
  const utils = trpc.useUtils();
  const stats = trpc.admin.stats.useQuery(undefined, { enabled: admin });
  const queue = trpc.admin.reports.useQuery({ status: "open" }, { enabled: admin });
  const businesses = trpc.admin.businesses.useQuery(undefined, { enabled: admin });
  const trust = trpc.admin.trustReports.useQuery({}, { enabled: admin && section === "trust" });
  const appeals = trpc.admin.appeals.useQuery({}, { enabled: admin && section === "trust" });
  const products = trpc.admin.products.useQuery(undefined, { enabled: admin && section === "products" });
  const categories = trpc.admin.categories.useQuery(undefined, { enabled: admin && section === "products" });
  const users = trpc.admin.users.useQuery(undefined, { enabled: admin && section === "users" });
  const alerts = trpc.admin.alerts.useQuery(undefined, { enabled: admin && section === "alerts" });
  const review = trpc.admin.reviewReport.useMutation({ onSuccess: async () => { await utils.admin.reports.invalidate(); await utils.admin.stats.invalidate(); } });
  const verify = trpc.admin.verifyBusiness.useMutation({ onSuccess: async () => { await utils.admin.businesses.invalidate(); await utils.admin.stats.invalidate(); } });
  const reviewTrust = trpc.admin.reviewTrustReport.useMutation({ onSuccess: async () => { await utils.admin.trustReports.invalidate(); await utils.admin.stats.invalidate(); } });
  const reviewAppeal = trpc.admin.reviewAppeal.useMutation({ onSuccess: () => utils.admin.appeals.invalidate() });
  const createProduct = trpc.admin.createProduct.useMutation({ onSuccess: async () => { await utils.admin.products.invalidate(); setNotice("Product added to the catalogue."); } });
  const createCategory = trpc.admin.createCategory.useMutation({ onSuccess: async () => { await utils.admin.categories.invalidate(); setNotice("Category saved."); } });
  const updateRole = trpc.admin.updateUserRole.useMutation({ onSuccess: () => utils.admin.users.invalidate() });
  const [notice, setNotice] = useState("");
  if (!admin) return null;
  const nav = [["Dashboard", "/admin"], ["Price Reports", "/admin/reports"], ["Business Verification", "/admin/businesses"], ["Trust Reports", "/admin/trust"], ["Products", "/admin/products"], ["Users", "/admin/users"], ["Price Alerts", "/admin/alerts"]];
  const title = section === "reports" ? "Price reports awaiting review" : section === "businesses" ? "Business verification queue" : section === "trust" ? "Trust reports and appeals" : section === "products" ? "Product catalogue" : section === "users" ? "User accounts" : section === "alerts" ? "Price alerts" : "PriceNaija admin workspace";
  return <div className="content-width page-content"><PageIntro eyebrow="PLATFORM OPERATIONS" title={title} description="Review submissions, keep verification decisions explicit and see platform activity."/><div className="admin-nav">{nav.map(([label, href]) => <Link className={window.location.pathname === href ? "active" : ""} key={href} href={href}>{label}</Link>)}</div>
    {notice && <p className="form-notice">{notice}</p>}
    {section === "overview" && <><div className="metric-grid admin-metrics">{[["Total users", stats.data?.users ?? "—"], ["Active users · 30 days", stats.data?.activeUsers ?? "—"], ["Price reports", stats.data?.reports ?? "—"], ["Verified reports", stats.data?.verifiedReports ?? "—"], ["Pending reports", stats.data?.pendingReports ?? "—"], ["Businesses", stats.data?.businesses ?? "—"], ["Verified businesses", stats.data?.verifiedBusinesses ?? "—"], ["Trust reports pending", stats.data?.pendingTrustReports ?? "—"], ["Average price change · 90d", stats.data?.averagePriceChangePct == null ? "—" : `${stats.data.averagePriceChangePct}%`]].map(([label, value]) => <div className="metric-card" key={label}><span>{label}</span><b>{value}</b><small>Live database totals</small></div>)}</div><div className="admin-analytics-grid"><section className="admin-table-card"><span className="eyebrow">DISCOVERY</span><h2>Most searched products</h2>{stats.data?.mostSearched?.length ? stats.data.mostSearched.map(item => <div className="dashboard-list-row" key={item.query}><b>{item.query}</b><small>{item.total} searches</small></div>) : <p className="empty-inline">Search analytics will appear after searches are submitted.</p>}</section><section className="admin-table-card"><span className="eyebrow">COMMUNITY REPORTS</span><h2>Most reported products</h2>{stats.data?.mostReported?.length ? stats.data.mostReported.map(item => <div className="dashboard-list-row" key={item.productName}><b>{item.productName}</b><small>{item.total} reports</small></div>) : <p className="empty-inline">No reported products yet.</p>}</section></div></>}
    {section === "reports" && <section className="admin-table-card"><div className="section-heading-inline"><div><span className="eyebrow">PRICE VERIFICATION</span><h2>Reports awaiting review</h2></div><ClipboardCheck size={19}/></div>{queue.data?.length ? queue.data.map(({ report, reporterName }) => <div className="review-row" key={report.id}><div className="review-mark">{report.evidenceUrl ? <img src={report.evidenceUrl} alt="Uploaded report evidence"/> : "₦"}</div><div className="review-data"><b>{report.productName} · {naira(report.priceNaira)}</b><small>{report.quantityLabel} · {report.city}, {report.state} · {report.market || "No market specified"}</small><small>Seller: {report.sellerName || "Not provided"} · Reporter: {reporterName || "Member"} · Seen {new Date(report.observedAt).toLocaleDateString("en-NG")}</small><small>Status: {report.status}</small>{report.reviewNote && <p>{report.reviewNote}</p>}{report.description && <p>{report.description}</p>}</div><div className="review-actions"><button onClick={() => review.mutate({ id: report.id, action: "verified" })}><Check size={14}/> Approve</button><button onClick={() => review.mutate({ id: report.id, action: "request_info", note: "Please add a clearer photo or more detail about the product, size, price or market location." })}>Request info</button><button className="reject-action" onClick={() => review.mutate({ id: report.id, action: "rejected", note: "Unable to verify the submitted details." })}>Reject</button></div></div>) : <div className="empty-inline"><b>No price reports awaiting review.</b><p>New and under-review submissions appear here until resolved.</p><Link href="/report" className="text-link">View report form <ArrowRight size={14}/></Link></div>}</section>}
    {section === "businesses" && <section className="admin-table-card"><div className="section-heading-inline"><div><span className="eyebrow">BUSINESS VERIFICATION</span><h2>Business queue</h2></div><BadgeCheck size={20}/></div>{businesses.data?.filter(item => !item.isDemo && item.verificationStatus === "pending").length ? businesses.data.filter(item => !item.isDemo && item.verificationStatus === "pending").map(business => <div className="review-row" key={business.id}><div className="review-mark">{business.name.slice(0, 1)}</div><div className="review-data"><b>{business.name}</b><small>{business.category} · {business.slug} · Status: {business.verificationStatus}</small></div><div className="review-actions"><button onClick={() => verify.mutate({ id: business.id, status: "verified" })}><Check size={14}/> Approve</button><button onClick={() => verify.mutate({ id: business.id, status: "rejected" })}>Reject</button></div></div>) : <div className="empty-inline"><b>No real business profiles awaiting review.</b><p>Demo profiles are never eligible for real-world verification.</p></div>}</section>}
    {section === "trust" && <div className="admin-trust-stack"><section className="admin-table-card"><div className="section-heading-inline"><div><span className="eyebrow">NEUTRAL REVIEW</span><h2>Community trust reports</h2></div><ShieldAlert size={20}/></div>{trust.data?.length ? trust.data.map(({ report, reporterName, businessName }) => <div className="review-row" key={report.id}><div className="review-mark">{report.evidenceUrl ? <img src={report.evidenceUrl} alt="Trust report evidence"/> : <ShieldAlert size={18}/>}</div><div className="review-data"><b>{report.reason} · {report.subjectName || businessName || "Transaction concern"}</b><small>Reporter: {reporterName || "Member"} · observed {new Date(report.observedAt).toLocaleDateString("en-NG")} · {report.status}</small><p>{report.description}</p>{report.businessId && <small>Linked business: {businessName || `#${report.businessId}`}</small>}</div><div className="review-actions"><button onClick={() => reviewTrust.mutate({ id: report.id, status: "under_review" })}>Review</button><button onClick={() => reviewTrust.mutate({ id: report.id, status: "resolved" })}>Resolve</button><button className="reject-action" onClick={() => reviewTrust.mutate({ id: report.id, status: "dismissed" })}>Dismiss</button></div></div>) : <div className="empty-inline"><b>No trust reports submitted.</b><p>Reports are private to moderators and never automatically label a business.</p></div>}</section><section className="admin-table-card"><span className="eyebrow">BUSINESS APPEALS</span><h2>Appeals queue</h2>{appeals.data?.length ? appeals.data.map(({ appeal, businessName, ownerName }) => <div className="review-row" key={appeal.id}><div className="review-data"><b>{businessName || `Business #${appeal.businessId}`} · {appeal.status}</b><small>Owner: {ownerName || "Business owner"} · {new Date(appeal.createdAt).toLocaleDateString("en-NG")}</small><p>{appeal.message}</p></div><div className="review-actions"><button onClick={() => reviewAppeal.mutate({ id: appeal.id, status: "under_review" })}>Review</button><button onClick={() => reviewAppeal.mutate({ id: appeal.id, status: "resolved" })}>Resolve</button><button className="reject-action" onClick={() => reviewAppeal.mutate({ id: appeal.id, status: "rejected" })}>Reject</button></div></div>) : <div className="empty-inline"><b>No business appeals yet.</b><p>Business owners can submit appeals through Trust &amp; Safety.</p></div>}</section></div>}
    {section === "products" && <div className="admin-products-layout"><section className="admin-table-card"><span className="eyebrow">CATALOGUE</span><h2>Add a product</h2><form className="stacked-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createProduct.mutate({ name: String(form.get("name")), category: String(form.get("category")), brand: String(form.get("brand") || ""), quantityLabel: String(form.get("quantity")), description: String(form.get("description") || "") }); }}><label>Product name<input name="name" required minLength={2}/></label><label>Category<select name="category">{categories.data?.map(category => <option key={category.id}>{category.name}</option>)}</select></label><label>Brand<input name="brand"/></label><label>Quantity / size<input name="quantity" required/></label><label>Description<textarea name="description" maxLength={2000}/></label><button className="btn-primary" disabled={createProduct.isPending}>Add product</button></form><hr/><h3>Add category</h3><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createCategory.mutate({ name: String(form.get("categoryName")) }); }}><input name="categoryName" required placeholder="Category name"/><button className="btn-outline">Save category</button></form></section><section className="admin-table-card"><span className="eyebrow">PRODUCTS & CATEGORIES</span><h2>Catalogue records</h2>{products.data?.map(({ product, categoryName }) => <div className="dashboard-list-row" key={product.id}><b>{product.name}</b><small>{categoryName || "Uncategorized"} · {product.isDemo ? "Demo" : "Catalogue"}</small></div>)}{categories.data?.map(category => <div className="dashboard-list-row" key={category.id}><b>{category.name}</b><small>Category</small></div>)}</section></div>}
    {section === "users" && <section className="admin-table-card"><span className="eyebrow">ACCOUNT MANAGEMENT</span><h2>Recent accounts</h2>{users.data?.map(account => <div className="review-row" key={account.id}><div className="review-mark"><Users size={18}/></div><div className="review-data"><b>{account.name || "PriceNaija member"}</b><small>{account.email} · {account.emailVerifiedAt ? "Email verified" : "Unverified"} · {new Date(account.createdAt).toLocaleDateString("en-NG")}</small></div>{account.accountRole !== "admin" && <div className="review-actions"><button onClick={() => updateRole.mutate({ userId: account.id, accountRole: account.accountRole === "business" ? "consumer" : "business" })}>{account.accountRole === "business" ? "Set consumer" : "Set business"}</button></div>}<span className="pending-badge">{account.accountRole}</span></div>)}</section>}
    {section === "alerts" && <section className="admin-table-card"><span className="eyebrow">PRICE ALERTS</span><h2>Recent alert activity</h2>{alerts.data?.map(({ alert, userName, productName }) => <div className="dashboard-list-row" key={alert.id}><b>{productName || "Product"} · {naira(alert.targetPriceNaira)}</b><small>{userName || "Member"} · {alert.isActive ? "Active" : "Triggered"}</small></div>)}</section>}
    <div className="admin-reminder"><ShieldAlert size={17}/><span>Only verified, non-demo reports are used by the Fair Price Checker. Review every submission before approval; community concerns remain neutral and appealable.</span></div>
  </div>;
}
