import { useState } from "react";
import { ArrowRight, MessageCircle, Plus, ShieldCheck, ThumbsUp } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { PageIntro, type ShellUser } from "@/components/PriceNaijaShell";

export default function CommunityPage({ user }: { user: ShellUser }) {
  const utils = trpc.useUtils();
  const posts = trpc.community.list.useQuery();
  const [showComposer, setShowComposer] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [commentText, setCommentText] = useState("");
  const comments = trpc.community.comments.useQuery({ postId: expanded ?? 1 }, { enabled: expanded !== null });
  const create = trpc.community.post.useMutation({ onSuccess: async () => { setNotice("Your post is now visible to the community."); setError(""); setShowComposer(false); await utils.community.list.invalidate(); }, onError: e => setError(e.message) });
  const like = trpc.community.like.useMutation({ onSuccess: async () => { await utils.community.list.invalidate(); }, onError: e => setError(e.message) });
  const comment = trpc.community.comment.useMutation({ onSuccess: async () => { setCommentText(""); setNotice("Comment added."); await utils.community.comments.invalidate(); await utils.community.list.invalidate(); }, onError: e => setError(e.message) });
  const report = trpc.community.report.useMutation({ onSuccess: () => { setNotice("The post was reported to moderators for review."); setError(""); }, onError: e => setError(e.message) });
  const submitPost = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const topic = String(form.get("topic")) as "prices" | "markets" | "products" | "shopping" | "tips"; create.mutate({ topic, title: String(form.get("title")), body: String(form.get("body")) }); };
  const submitComment = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (expanded) comment.mutate({ postId: expanded, body: commentText }); };
  const reportPost = (postId: number) => { if (!user) { window.location.href = "/login"; return; } const reason = window.prompt("Why should a moderator review this post?"); if (reason?.trim()) report.mutate({ postId, reason: reason.trim() }); };
  return <div className="content-width page-content"><PageIntro eyebrow="PRICE NAIJA COMMUNITY" title="Better market knowledge, together." description="Share prices, shopping experiences and practical tips. Keep it helpful, respectful and grounded in what you’ve seen." action={user ? <button className="btn-primary" onClick={() => setShowComposer(value => !value)}><Plus size={16}/> Start a conversation</button> : <Link className="btn-primary" href="/login">Log in to post <ArrowRight size={14}/></Link>}/>
    {showComposer && user && <form className="community-compose" onSubmit={submitPost}><label>Topic<select name="topic"><option value="prices">Prices</option><option value="markets">Markets</option><option value="products">Products</option><option value="shopping">Shopping</option><option value="tips">Tips</option></select></label><label>Title<input name="title" required minLength={5} maxLength={180} placeholder="What would you like to share?"/></label><label>Details<textarea name="body" required minLength={10} maxLength={4000} rows={4}/></label><button className="btn-primary" disabled={create.isPending}>{create.isPending ? "Posting…" : "Post to community"}<ArrowRight size={15}/></button></form>}
    {notice && <p className="form-notice">{notice}</p>}{error && <p className="form-alert">{error}</p>}
    <div className="community-layout"><div className="community-feed">{posts.data?.length ? posts.data.map(post => <article key={post.id} className="community-post"><div className="post-avatar">{post.authorName.slice(0, 1).toUpperCase()}</div><div className="post-body"><div className="post-meta"><span>{post.authorName}</span><span>·</span><span>{new Date(post.createdAt).toLocaleDateString("en-NG")}</span><span className="topic-chip">{post.topic}</span></div><h3>{post.title}</h3><p>{post.body}</p><div className="post-actions"><button onClick={() => user ? like.mutate({ postId: post.id }) : window.location.assign("/login")} disabled={like.isPending}><ThumbsUp size={15}/> Like · {post.likeCount}</button><button onClick={() => setExpanded(expanded === post.id ? null : post.id)}><MessageCircle size={15}/> {expanded === post.id ? "Hide comments" : `Comment · ${post.commentCount}`}</button><button onClick={() => reportPost(post.id)}><ShieldCheck size={15}/> Report</button></div>{expanded === post.id && <div className="community-comments">{comments.data?.map(item => <div className="community-comment" key={item.comment.id}><b>{item.authorName || "Member"}</b><p>{item.comment.body}</p></div>)}{user ? <form onSubmit={submitComment} className="comment-compose"><label htmlFor={`comment-${post.id}`}>Add a comment</label><textarea id={`comment-${post.id}`} value={commentText} onChange={event => setCommentText(event.target.value)} minLength={2} maxLength={2000} required rows={2}/><button className="btn-outline" disabled={comment.isPending}>{comment.isPending ? "Sending…" : "Comment"}</button></form> : <Link href="/login" className="text-link">Log in to comment</Link>}</div>}</div></article>) : <div className="empty-state community-empty"><span className="empty-icon"><MessageCircle/></span><h3>No community posts yet.</h3><p>Start a conversation about prices, markets, products, shopping or tips.</p>{user && <button className="btn-primary" onClick={() => setShowComposer(true)}>Create the first post <ArrowRight size={14}/></button>}</div>}</div>
      <aside className="community-aside"><div className="surface-card"><span className="aside-icon">✳</span><h3>Good context travels.</h3><p>Share what you personally observed. A community post is not automatically a verified price.</p><Link href="/trust-safety" className="text-link">Community guidelines <ArrowRight size={14}/></Link></div><div className="surface-card community-topics"><b>Conversation topics</b>{["Prices", "Markets", "Products", "Shopping", "Tips"].map((topic, index) => <div key={topic}><span>0{index + 1}</span>{topic}<ArrowRight size={14}/></div>)}</div></aside>
    </div></div>;
}
