import { ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, ChevronRight, CircleHelp, MapPin, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useState } from "react";
import { DemoTag, SectionTitle } from "@/components/PriceNaijaShell";
import { ProductCard } from "@/components/ProductCard";
import { demoProducts, locations, naira } from "@/lib/priceData";

export default function Home() {
  const [, setLocation] = useLocation(); const [query, setQuery] = useState(""); const trending = demoProducts.slice(0, 3); const drops = demoProducts.filter(p => p.change < 0).slice(0, 2);
  return <div className="home-page">
    <section className="hero-wrap"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="pulse-dot"/> PRICE TRANSPARENCY, FOR EVERYDAY LIFE</div><h1>Know the price.<br/><em>Save your money.</em></h1><p className="hero-lede">Compare prices across Nigeria before you buy. Find a fair price, see what neighbours are paying, and make every naira count.</p>
      <form className="hero-search" onSubmit={e => { e.preventDefault(); setLocation(`/search?q=${encodeURIComponent(query)}`); }}><Search size={20}/><input aria-label="Search products" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search rice, cooking gas, iPhone, cement…"/><button type="submit">Search <ArrowRight size={16}/></button></form>
      <div className="popular-searches"><span>Popular:</span>{["Rice", "Cooking Gas", "Cement", "Phones", "Eggs", "Food"].map(word => <button key={word} onClick={() => setLocation(`/search?q=${encodeURIComponent(word)}`)}>{word}</button>)}</div>
      <div className="hero-ctas"><Link href="/search" className="btn-primary">Compare Prices <ArrowRight size={16}/></Link><Link href="/report" className="btn-outline">Report a Price <ArrowUpRight size={15}/></Link></div>
    </div><div className="hero-visual"><div className="hero-visual-label"><span className="market-mark">₦</span><div><b>Your market, made clearer</b><small>Local insight. Better decisions.</small></div><Sparkles size={17}/></div><div className="hero-price-panel"><div className="hero-price-head"><span>25kg rice · Lagos</span><DemoTag/></div><div className="hero-number">{naira(54200)}<span className="mini-trend"><ArrowUpRight size={13}/> 4.8%</span></div><div className="hero-price-caption">Average sample price <span>Illustrative demo data</span></div><svg className="hero-chart" viewBox="0 0 420 120" preserveAspectRatio="none" aria-label="Illustrative sample price trend"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#087443" stopOpacity=".17"/><stop offset="1" stopColor="#087443" stopOpacity="0"/></linearGradient></defs><path d="M0 96 C35 90 39 72 69 76 S105 84 132 69 S163 76 194 56 S231 63 253 44 S284 51 310 35 S349 55 376 20 S401 34 420 12 V120 H0Z" fill="url(#fill)"/><path d="M0 96 C35 90 39 72 69 76 S105 84 132 69 S163 76 194 56 S231 63 253 44 S284 51 310 35 S349 55 376 20 S401 34 420 12" fill="none" stroke="#087443" strokeWidth="3" strokeLinecap="round"/></svg><div className="hero-chart-labels"><span>May 1</span><span>May 8</span><span>May 15</span><span>May 22</span><span>Today</span></div><div className="hero-panel-footer"><span><i className="verified-dot"/> Verified market data is the goal</span><Link href="/markets">Explore markets <ArrowRight size={13}/></Link></div></div><div className="floating-saving"><span className="saving-icon"><ArrowDownRight size={18}/></span><div><b>Find a better deal</b><small>Compare before you buy</small></div></div><div className="hero-annotation"><MapPin size={14}/> Across 8 Nigerian cities</div></div></div>
      <div className="hero-trust-strip"><span><ShieldCheck size={17}/> Community-powered</span><span><BadgeCheck size={17}/> Verification before trust</span><span><CircleHelp size={17}/> Clear price context</span></div>
    </section>
    <section className="section-pad trending-section"><div className="content-width"><SectionTitle eyebrow="KNOW WHAT'S MOVING" title="Trending prices" detail="A quick read on everyday essentials. These sample figures are for demonstration only." href="/search" linkText="Compare all"/><div className="demo-banner"><DemoTag/><span>Sample figures only — not live or independently verified prices.</span></div><div className="product-grid">{trending.map(product => <ProductCard key={product.slug} product={product}/>)}</div></div></section>
    <section className="section-pad soft-section"><div className="content-width drop-layout"><div className="drop-intro"><div className="eyebrow gold-eyebrow">A LITTLE MORE ROOM IN YOUR BUDGET</div><h2>Prices dropping</h2><p>Spot a price moving in the right direction. Compare recent examples before you decide.</p><Link className="btn-dark" href="/deals">Explore deals <ArrowRight size={16}/></Link></div><div className="drop-list">{drops.map(product => <Link key={product.slug} href={`/products/${product.slug}`} className="drop-card"><span className="drop-icon">{product.icon}</span><div className="drop-main"><b>{product.name}</b><small>{product.quantity} · sample comparison</small><div className="drop-prices"><del>{naira(Math.round(product.average * 1.065))}</del><strong>{naira(product.low)}</strong></div></div><span className="drop-percent"><ArrowDownRight size={15}/>{Math.abs(product.change)}%</span><ChevronRight size={16} className="drop-chevron"/></Link>)}</div></div></section>
    <section className="section-pad"><div className="content-width"><SectionTitle eyebrow="LOCAL CONTEXT MATTERS" title="Explore prices near you" detail="Prices can vary from one city to the next. Choose a location to explore the local picture." href="/markets" linkText="Open market map"/><div className="market-preview"><div className="market-copy"><span className="market-kicker"><MapPin size={14}/> YOUR MARKET, YOUR VIEW</span><h3>One country.<br/><span>Many price stories.</span></h3><p>Browse sample comparisons by city. As verified reports arrive, local trends will become clearer.</p><Link className="text-link" href="/markets">Explore markets <ArrowRight size={15}/></Link><div className="city-pills">{locations.slice(0, 6).map(city => <Link href={`/markets?city=${encodeURIComponent(city)}`} key={city}>{city}</Link>)}</div></div><div className="market-map-art" aria-label="Illustrative Nigeria market map"><div className="map-grid"/><svg viewBox="0 0 390 320" role="img" aria-label="Illustrative outline of Nigeria and sample city markers"><path d="M73 55 105 41l22 13 19-11 25 14 23-8 20 20 24 3 8 20 24 9-2 24 18 16-11 20 12 21-22 10-4 24-27 9-11 25-29-5-17 15-23-13-18 8-13-17-24 2-10-21-23-1-8-20-19-10 6-24-14-12 9-19-10-19 12-16-2-24 21-9 7-22Z" fill="#e9f3ed" stroke="#9ab9a6" strokeWidth="2.5" strokeLinejoin="round"/><path d="M84 95 137 98l49-7 31 17 46-8m-163 50 49-11 42 10 49-15 38 15m-156 51 47-15 32 19 45-12 32 9" fill="none" stroke="#c6d7cc" strokeWidth="1.5" strokeDasharray="4 6"/><g className="map-pins"><circle cx="138" cy="197" r="7"/><circle cx="182" cy="157" r="7"/><circle cx="226" cy="122" r="7"/><circle cx="120" cy="149" r="6"/><circle cx="189" cy="92" r="6"/><circle cx="253" cy="161" r="6"/><circle cx="194" cy="222" r="6"/><circle cx="164" cy="126" r="6"/></g></svg><div className="map-label l-lagos">Lagos <b>Demo</b></div><div className="map-label l-abuja">Abuja <b>Demo</b></div><div className="map-label l-kano">Kano <b>Demo</b></div><div className="map-legend"><i/> Sample locations <i className="legend-pale"/> More cities</div></div></div></div></section>
    <section className="section-pad how-section"><div className="content-width"><SectionTitle eyebrow="SIMPLE AS THAT" title="A little more confidence, before checkout"/><div className="how-grid">{[{n:"01",title:"Search",copy:"Find the product, service or everyday essential you need.",icon:"⌕"},{n:"02",title:"Compare",copy:"See what prices look like across sellers and locations.",icon:"↗"},{n:"03",title:"Save",copy:"Choose with more context — and keep track of what matters.",icon:"₦"}].map(step => <div className="how-card" key={step.n}><span className="how-number">{step.n}</span><span className="how-icon">{step.icon}</span><h3>{step.title}</h3><p>{step.copy}</p></div>)}</div></div></section>
    <section className="closing-cta"><div><div className="eyebrow">BETTER CHOICES START WITH BETTER CONTEXT</div><h2>Help make price discovery<br/>a little easier for everyone.</h2><p>Share a price you saw or start by comparing what’s out there.</p></div><div className="closing-actions"><Link className="btn-white" href="/search">Compare prices <ArrowRight size={15}/></Link><Link className="btn-outline-light" href="/report">Report a price</Link></div></section>
  </div>;
}
