import { useState } from "react";
import { Activity, ArrowRight, Check, ChevronDown, MapPin, ShieldCheck, Users } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { demoProducts, locations, naira } from "@/lib/priceData";
import { DemoTag, PageIntro } from "@/components/PriceNaijaShell";

const coords: Record<string, [number, number]> = { Lagos: [130, 205], Abuja: [190, 158], Ibadan: [116, 158], "Port Harcourt": [198, 225], Benin: [154, 182], Kano: [196, 94], Enugu: [224, 182], Kaduna: [164, 126] };
const cityForSlug = (slug?: string) => locations.find(city => city.toLowerCase().replace(/\s+/g, "-") === slug?.toLowerCase()) || "Lagos";
export default function MarketPage({ initialLocation }: { initialLocation?: string }) {
  const [slug, setSlug] = useState(demoProducts[0].slug);
  const [city, setCity] = useState(cityForSlug(initialLocation));
  const product = demoProducts.find(item => item.slug === slug) ?? demoProducts[0];
  const summary = trpc.products.marketSummary.useQuery({ productName: product.name });
  const verifiedCity = summary.data?.find(row => row.city.toLowerCase() === city.toLowerCase());
  const verifiedRows = summary.data || [];
  const price = verifiedCity?.average ?? product.locationPrices[city] ?? product.average;
  const displayRows = verifiedRows.length ? verifiedRows : locations.map(name => ({ city: name, average: product.locationPrices[name] ?? product.average, lowest: product.locationPrices[name] ?? product.low, highest: product.locationPrices[name] ?? product.high, count: 0, lastUpdated: null, state: name }));
  const max = Math.max(...displayRows.map(row => row.average));
  const min = Math.min(...displayRows.map(row => row.average));
  const active = displayRows.find(row => row.city.toLowerCase() === city.toLowerCase());
  return <div className="content-width page-content"><PageIntro eyebrow="NIGERIA MARKET PRICE MAP" title="See how prices shift from place to place." description="Choose a product, explore city comparisons and see whether the information comes from verified reports or illustrative sample data." action={verifiedRows.length ? <span className="verified-label"><Check size={13}/> Verified reports</span> : <DemoTag/>}/>
    <div className="market-controls"><label><span>PRODUCT</span><select value={slug} onChange={event => setSlug(event.target.value)}>{demoProducts.map(item => <option value={item.slug} key={item.slug}>{item.name} · {item.quantity}</option>)}</select><ChevronDown size={15}/></label><label><span>SELECTED CITY</span><select value={city} onChange={event => setCity(event.target.value)}>{locations.map(item => <option key={item}>{item}</option>)}</select><ChevronDown size={15}/></label></div>
    <div className="market-data-note">{verifiedRows.length ? <span className="verified-label"><Check size={13}/> Verified data</span> : <span className="demo-tag"><i/> Demo data</span>} {verifiedRows.length ? "Recent verified community reports only. The report count and observation date are shown for each city." : "Illustrative sample comparisons only. They do not represent live or independently verified prices."}</div>
    <div className="map-detail-layout"><section className="large-map-card"><div className="map-card-header"><div><span className="eyebrow">PRICE LEVELS BY CITY</span><h2>{product.name}</h2></div><span className="map-period"><Activity size={14}/> {verifiedRows.length ? "Verified reports" : "Sample view"}</span></div><div className="large-map-visual"><div className="map-grid"/><svg viewBox="0 0 390 320" role="img" aria-label="Schematic map of Nigeria with selectable city price markers"><path d="M73 55 105 41l22 13 19-11 25 14 23-8 20 20 24 3 8 20 24 9-2 24 18 16-11 20 12 21-22 10-4 24-27 9-11 25-29-5-17 15-23-13-18 8-13-17-24 2-10-21-23-1-8-20-19-10 6-24-14-12 9-19-10-19 12-16-2-24 21-9 7-22Z" fill="#edf4ef" stroke="#9bb8a6" strokeWidth="2.5" strokeLinejoin="round"/><path d="M84 95 137 98l49-7 31 17 46-8m-163 50 49-11 42 10 49-15 38 15m-156 51 47-15 32 19 45-12 32 9" fill="none" stroke="#c8d8ce" strokeWidth="1.5" strokeDasharray="4 6"/>{displayRows.filter(row => coords[row.city]).map(row => { const [x, y] = coords[row.city]; const ratio = max === min ? 0.5 : (row.average - min) / (max - min); return <g key={row.city} onClick={() => setCity(row.city)} role="button" tabIndex={0} onKeyDown={event => event.key === "Enter" && setCity(row.city)} className="map-city-pin"><circle cx={x} cy={y} r={row.city === city ? 13 : 10} fill={row.city === city ? "#087443" : ratio > 0.7 ? "#abcbb5" : "#d9e8de"} stroke="white" strokeWidth="3"/><circle cx={x} cy={y} r="3" fill="white"/></g>; })}</svg>{locations.map(name => { const [x, y] = coords[name]; return <button key={name} className={`city-map-label ${city === name ? "selected" : ""}`} style={{ left: `${x / 390 * 100}%`, top: `${y / 320 * 100}%` }} onClick={() => setCity(name)}>{name}</button>; })}<div className="map-legend"><span><i className="level-low"/> Lower range</span><span><i className="level-high"/> Higher range</span></div></div></section>
      <aside className="city-insight-card"><span className="eyebrow">CITY SNAPSHOT</span><div className="city-big-name"><MapPin size={17}/>{city}</div><span className="insight-product">{product.name} · {product.quantity}</span><div className="city-price">{naira(price)}{verifiedCity ? <span className="verified-label"><Check size={13}/> Verified average</span> : <DemoTag/>}</div><div className="snapshot-grid"><div><small>{verifiedCity ? "Lowest verified" : "Lowest sample"}</small><b>{naira(active?.lowest ?? product.low)}</b></div><div><small>{verifiedCity ? "Highest verified" : "Highest sample"}</small><b>{naira(active?.highest ?? product.high)}</b></div><div><small>Reports</small><b>{verifiedCity ? verifiedCity.count : "—"}</b></div><div><small>Last updated</small><b>{verifiedCity?.lastUpdated ? new Date(verifiedCity.lastUpdated).toLocaleDateString("en-NG") : "Sample"}</b></div></div><div className="insight-divider"/><p><ShieldCheck size={15}/>{verifiedCity ? "Based on recent verified community reports." : "No verified reports yet for this city and product."}</p><Link href={`/products/${product.slug}`} className="btn-primary full-width">Compare this product <ArrowRight size={15}/></Link></aside>
    </div>
    <section className="city-table-card"><div className="section-heading-inline"><div><span className="eyebrow">CITY BY CITY</span><h2>{verifiedRows.length ? "Recent verified price comparison" : "Sample price comparison"}</h2></div><Users size={18} className="green-icon"/></div><div className="city-table">{locations.map(name => { const row = displayRows.find(item => item.city === name); const avg = row?.average ?? product.locationPrices[name]; return <button onClick={() => setCity(name)} className={city === name ? "active" : ""} key={name}><span>{name}</span><b>{naira(avg)}</b><span className="tiny-track"><i style={{ width: `${max ? avg / max * 100 : 0}%` }}/></span><small>{row && verifiedRows.length ? `${row.count} verified` : "Demo"}</small></button>; })}</div></section>
    <div className="fair-callout"><div className="fair-icon">?</div><div><b>Need a quick benchmark?</b><p>Check the fair-price estimate using recent verified reports.</p></div><Link className="btn-outline" href={`/fair-price?product=${encodeURIComponent(product.name)}`}>Fair Price Checker <ArrowRight size={15}/></Link></div>
  </div>;
}
