import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ImagePlus, MapPin, ShieldCheck, UploadCloud } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { categories, demoProducts, locations } from "@/lib/priceData";
import type { ShellUser } from "@/components/PriceNaijaShell";

const locationState:Record<string,string>={Lagos:"Lagos",Abuja:"FCT",Ibadan:"Oyo","Port Harcourt":"Rivers",Benin:"Edo",Kano:"Kano",Enugu:"Enugu",Kaduna:"Kaduna"};
export default function ReportPage({user}:{user:ShellUser}){
 const [sent,setSent]=useState(false);const [photo,setPhoto]=useState("");const [photoName,setPhotoName]=useState("");const [error,setError]=useState("");const [city,setCity]=useState("Lagos");const productCatalogue=trpc.products.search.useQuery({});const submit=trpc.products.submit.useMutation({onSuccess:()=>setSent(true),onError:e=>setError(e.message)});
 if(sent)return <div className="content-width page-content"><div className="submission-success"><span className="success-icon"><CheckCircle2/></span><span className="eyebrow">YOUR CONTRIBUTION MATTERS</span><h1>Submission received ✓</h1><p>Thank you for helping Nigerians discover better prices.</p><span className="pending-status">Pending verification</span><small>Your report will not appear as a verified price until an administrator reviews it.</small><Link href="/dashboard" className="btn-primary">View my reports <ArrowRight size={15}/></Link><Link href="/search" className="text-link">Continue comparing prices</Link></div></div>;
 const onFile=(file?:File)=>{if(!file)return;setError("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Choose a JPG, PNG or WebP photo.");return}if(file.size>3*1024*1024){setError("Photo must be 3MB or smaller.");return}const reader=new FileReader();reader.onload=()=>{setPhoto(String(reader.result));setPhotoName(file.name)};reader.readAsDataURL(file)};
 return <div className="content-width page-content report-layout"><div className="report-main"><Link href="/" className="back-link"><ArrowLeft size={15}/> Home</Link><div className="eyebrow">COMMUNITY-POWERED PRICE TRANSPARENCY</div><h1>Report a price.</h1><p className="report-lede">Help someone nearby know what to expect before they buy. Every report starts pending and is reviewed before it can inform verified comparisons.</p>
 {!user&&<div className="auth-required-banner"><ShieldCheck size={18}/><div><b>Sign in to keep track of your contribution.</b><span>You can create a consumer account in a moment.</span></div><Link href="/login">Log in <ArrowRight size={14}/></Link></div>}
 <form className="report-form" onSubmit={e=>{e.preventDefault();setError("");if(!user){setError("Please log in or create an account before submitting a report.");return}const f=new FormData(e.currentTarget as HTMLFormElement);const productName=String(f.get("productName"));const quantityLabel=String(f.get("quantityLabel"));const matched=productCatalogue.data?.find(item=>item.name.toLowerCase()===productName.trim().toLowerCase()&&item.quantityLabel===quantityLabel);submit.mutate({productId:matched?.id,productName,category:String(f.get("category")),brand:String(f.get("brand")||""),quantityLabel,priceNaira:Number(f.get("priceNaira")),city,state:locationState[city]||city,market:String(f.get("market")||""),sellerName:String(f.get("sellerName")||""),sellerContact:String(f.get("sellerContact")||""),description:String(f.get("description")||""),evidenceDataUrl:photo||undefined,observedAt:String(f.get("observedAt")||"")})}}>
 <div className="form-section-title"><span>01</span><div><b>What did you find?</b><small>Product details help others compare like for like.</small></div></div><div className="form-grid"><label className="field-span-2">Product name<input name="productName" list="product-options" required minLength={2} placeholder="e.g. Long-grain rice"/><datalist id="product-options">{productCatalogue.data?.map(p=><option value={p.name} key={p.slug}/>)}{demoProducts.map(p=><option value={p.name} key={`demo-${p.slug}`}/>)}</datalist></label><label>Category<select name="category" required>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Brand (optional)<input name="brand" placeholder="Brand or type"/></label><label>Quantity / size<input name="quantityLabel" required placeholder="e.g. 25kg bag"/></label><label>Price (₦)<input name="priceNaira" type="number" required min="1" step="1" placeholder="e.g. 50000"/></label></div>
 <div className="form-section-title"><span>02</span><div><b>Where and when?</b><small>Local context makes a price more useful.</small></div></div><div className="form-grid"><label>City / location<select value={city} onChange={e=>setCity(e.target.value)}>{locations.map(l=><option key={l}>{l}</option>)}</select></label><label>State<input value={locationState[city]||city} readOnly/></label><label>Market / area<input name="market" placeholder="e.g. Mile 12 Market"/></label><label>Date seen<input name="observedAt" type="date" max={new Date().toISOString().slice(0,10)}/></label></div>
 <div className="form-section-title"><span>03</span><div><b>Seller and evidence</b><small>Evidence is optional but helps reviewers confirm details.</small></div></div><div className="form-grid"><label>Seller / business name<input name="sellerName" placeholder="Optional"/></label><label>Seller contact (optional)<input name="sellerContact" placeholder="Phone or email"/></label><label className="field-span-2">Description<textarea name="description" rows={3} placeholder="Share anything helpful, like packaging or shelf details."/></label></div>
 <label className="upload-zone">{photo?<><img src={photo} alt="Price evidence preview"/><span><b>{photoName}</b><small>Click to replace · maximum 3MB</small></span></>:<><span className="upload-icon"><UploadCloud/></span><span><b>Add a photo (optional)</b><small>JPG, PNG or WebP · up to 3MB</small></span><span className="upload-button"><ImagePlus size={15}/> Browse</span></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>onFile(e.target.files?.[0])}/></label>
 {error&&<div className="form-alert">{error}</div>}<div className="report-form-bottom"><span><ShieldCheck size={16}/> Your report starts as <b>Pending verification</b>.</span><button type="submit" disabled={submit.isPending} className="btn-primary">{submit.isPending?"Submitting…":"Submit Price"}<ArrowRight size={16}/></button></div>
 </form></div><aside className="report-sidebar"><div className="report-aside-card"><span className="aside-icon">✓</span><h3>Helpful reports<br/>make fairer markets.</h3><p>Price reports are reviewed by the PriceNaija team. We never automatically treat a community submission as a verified fact.</p><div className="review-step"><i>1</i><span><b>Submitted</b><small>Your report is received.</small></span></div><div className="review-step"><i>2</i><span><b>Reviewed</b><small>A moderator checks the details.</small></span></div><div className="review-step"><i>3</i><span><b>Verified or declined</b><small>Status updates on your dashboard.</small></span></div></div><div className="report-privacy"><MapPin size={16}/><b>Share only what you know.</b><p>A seller's contact is optional and is never shown publicly from this form.</p></div></aside></div>
}
