import { Bell, Bookmark, CheckCircle2, Clock3, Search, TrendingDown, UserRound } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { demoProducts, naira } from "@/lib/priceData";
import { PageIntro, type ShellUser } from "@/components/PriceNaijaShell";

export default function UserDashboardPage({ user }: { user: ShellUser }) {
  const enabled = Boolean(user);
  const utils = trpc.useUtils();
  const saved = trpc.account.saved.useQuery(undefined, { enabled });
  const alerts = trpc.account.alerts.useQuery(undefined, { enabled });
  const reports = trpc.products.mine.useQuery(undefined, { enabled });
  const searches = trpc.account.recentSearches.useQuery(undefined, { enabled });
  const notifications = trpc.account.notifications.useQuery(undefined, { enabled });
  const read = trpc.account.markNotificationRead.useMutation({ onSuccess: () => utils.account.notifications.invalidate() });
  const removeAlert = trpc.account.removeAlert.useMutation({ onSuccess: () => utils.account.alerts.invalidate() });
  if (!user) return <div className="content-width page-content"><PageIntro eyebrow="YOUR PRICE TOOLKIT" title="Save prices worth coming back to." description="Sign in to manage saved products, price alerts and your community contributions."/><div className="empty-state"><span className="empty-icon"><UserRound/></span><h3>Log in to open your dashboard.</h3><Link href="/login" className="btn-primary">Log in <CheckCircle2 size={15}/></Link></div></div>;
  const verified = reports.data?.filter(row => row.status === "verified").length ?? 0;
  const sampleSaving = saved.data?.reduce((sum, row) => { const demo = demoProducts.find(item => item.slug === row.product.slug); return sum + (demo ? Math.max(0, demo.average - demo.low) : 0); }, 0) ?? 0;
  return <div className="content-width page-content"><PageIntro eyebrow="YOUR PRICE TOOLKIT" title={`Welcome back${user.name ? `, ${user.name.split(" ")[0]}` : ""} 👋`} description="Pick up where you left off, follow the products you care about and see what you’ve contributed." action={<Link className="btn-outline" href="/profile">Edit profile <UserRound size={15}/></Link>}/>
    <div className="metric-grid"><Metric icon={<Bookmark/>} label="Saved products" value={String(saved.data?.length ?? 0)} helper="Your watchlist"/><Metric icon={<Bell/>} label="Price alerts" value={String(alerts.data?.filter(row => row.alert.isActive).length ?? 0)} helper="Active thresholds"/><Metric icon={<CheckCircle2/>} label="Verified contributions" value={String(verified)} helper={`${reports.data?.length ?? 0} submitted reports`}/><Metric icon={<TrendingDown/>} label="Sample price gap" value={naira(sampleSaving)} helper="Illustrative only — not actual savings"/></div>
    <div className="user-dashboard-grid"><section className="surface-card"><div className="section-heading-inline"><div><span className="eyebrow">YOUR WATCHLIST</span><h2>Saved products</h2></div><Bookmark size={18}/></div>{saved.data?.length ? saved.data.map(({ saved: entry, product }) => { const demo = demoProducts.find(item => item.slug === product.slug); return <Link className="dashboard-product-row" href={`/products/${product.slug}`} key={entry.id}><span className="product-emoji small">{demo?.icon || "◈"}</span><span><b>{product.name}</b><small>{demo ? "Sample comparison · not a live quote" : "Catalogue product"}</small></span><strong>{demo ? naira(demo.low) : "No verified price yet"}</strong></Link>; }) : <div className="empty-inline"><b>No saved products yet.</b><p>Save a product to make it easy to check again.</p><Link href="/search" className="text-link">Browse prices</Link></div>}</section>
      <section className="surface-card"><div className="section-heading-inline"><div><span className="eyebrow">PRICE WATCH</span><h2>Your alerts</h2></div><Bell size={18}/></div>{alerts.data?.length ? alerts.data.map(({ alert, product }) => <div className="dashboard-list-row" key={alert.id}><span><b>{product.name}</b><small>Notify below {naira(alert.targetPriceNaira)} · {alert.isActive ? "Active" : "Triggered"}</small></span>{alert.isActive && <button className="link-button" onClick={() => removeAlert.mutate({ id: alert.id })}>Turn off</button>}</div>) : <div className="empty-inline"><b>No price alerts yet.</b><p>Open a product and choose a target price to be notified.</p><Link href="/search" className="text-link">Explore products</Link></div>}</section>
      <section className="surface-card"><div className="section-heading-inline"><div><span className="eyebrow">YOUR CONTRIBUTIONS</span><h2>Reported prices</h2></div><Clock3 size={18}/></div><div className="dashboard-stat-line"><span>Prices submitted</span><b>{reports.data?.length ?? 0}</b></div><div className="dashboard-stat-line"><span>Verified</span><b>{verified}</b></div>{reports.data?.slice(0,4).map(report => <div className="dashboard-list-row" key={report.id}><b>{report.productName} · {naira(report.priceNaira)}</b><small>{report.city} · <span className={`status-${report.status}`}>{report.status}</span></small></div>)}{!reports.data?.length&&<p className="empty-inline">Your price contributions will appear here after submission.</p>}<Link href="/report" className="text-link">Report a price</Link></section>
      <section className="surface-card"><div className="section-heading-inline"><div><span className="eyebrow">PICK UP SEARCH</span><h2>Recent searches</h2></div><Search size={18}/></div>{searches.data?.length ? searches.data.slice(0,6).map(item => <Link className="dashboard-list-row" href={`/search?q=${encodeURIComponent(item.query)}`} key={item.id}><b>{item.query}</b><small>{[item.category,item.city].filter(Boolean).join(" · ") || new Date(item.createdAt).toLocaleDateString("en-NG")}</small></Link>) : <div className="empty-inline"><b>No recent searches.</b><p>Searches you submit will be saved to your account.</p><Link href="/search" className="text-link">Search products</Link></div>}</section></div>
    <section className="surface-card dashboard-notifications"><div className="section-heading-inline"><div><span className="eyebrow">ACCOUNT ACTIVITY</span><h2>Notifications</h2></div><Bell size={18}/></div>{notifications.data?.length ? notifications.data.map(item => <div className={`dashboard-list-row ${item.isRead ? "read" : "unread"}`} key={item.id}><span><b>{item.title}</b><small>{item.message}</small><small>{new Date(item.createdAt).toLocaleString("en-NG")}</small></span>{!item.isRead && <button className="link-button" onClick={() => read.mutate({ id: item.id })}>Mark read</button>}</div>) : <p className="empty-inline">Important account activity and price-alert notifications appear here.</p>}</section>
  </div>;
}
function Metric({ icon, label, value, helper }: { icon: ReactNode; label: string; value: string; helper: string }) { return <div className="metric-card"><span className="metric-icon">{icon}</span><span>{label}</span><b>{value}</b><small>{helper}</small></div>; }
